# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Project
  pod 'Alamofire',                '~> 4.5'
  pod 'AlamofireObjectMapper',    '5.0.0'

  pod 'RxSwift',                  '4.1.0'
end
